catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - cached-factory@0.1.0
  - ts-api-utils@2.2.0
packages:
  - ./
  - playground
catalog:
  '@schplitt/eslint-config': ^1.2.0
  bumpp: ^10.3.2
  eslint: ^9.39.2
  nitro: 3.0.1-alpha.1
  tinyexec: ^1.0.2
  tsdown: ^0.18.4
  typescript: ^5.9.3
  vitest: ^4.0.16
onlyBuiltDependencies:
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2



