catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - cached-factory@0.1.0
  - ts-api-utils@2.2.0
  - undici-types@6.21.0
packages:
  - ./
  - playground
catalog:
  '@schplitt/eslint-config': ^1.3.1
  '@types/spinnies': ^0.5.3
  bumpp: ^10.4.1
  c12: ^4.0.0-beta.2
  citty: ^0.2.0
  consola: ^3.4.2
  eslint: ^10.0.0
  jszip: ^3.10.1
  memfs: ^4.56.10
  nitro: 3.0.1-alpha.2
  pathe: ^2.0.3
  pkg-types: ^2.3.0
  spinnies: ^0.5.1
  tinyexec: ^1.0.2
  tsdown: ^0.20.3
  typescript: ^5.9.3
  vitest: ^4.0.18
onlyBuiltDependencies:
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
