import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: {
    'index': './src/index.ts',
    'types': './src/types/index.ts',
    'utils': './src/utils/index.ts',
    'cli/index': './src/cli/index.ts',
    'client': './src/client.ts',
  },
  target: ['es2023'],
  format: 'esm',
  clean: true,
  dts: true,
  outDir: './dist',
  unbundle: true,
  copy: [
    {
      from: './src/module/runtime/**/*.ts',
      flatten: false,
    },
  ],
  inlineOnly: [
    '@c8y/client',
    'asynckit',
    'b2a',
    'call-bind-apply-helpers',
    'combined-stream',
    'cometd-nodejs-client',
    'cometd',
    'cross-fetch',
    'delayed-stream',
    'dunder-proto',
    'encoding',
    'es-define-property',
    'es-errors',
    'es-object-atoms',
    'es-set-tostringtag',
    'form-data',
    'function-bind',
    'get-intrinsic',
    'get-proto',
    'gopd',
    'has-symbols',
    'has-tostringtag',
    'hasown',
    'iconv-lite',
    'isomorphic-cometd',
    'math-intrinsics',
    'mime-db',
    'mime-types',
    'node-fetch',
    'safer-buffer',
    'tr46',
    'tslib',
    'webidl-conversions',
    'whatwg-url',
  ],

})
