import { c8yManifest } from 'c8y-nitro/runtime'
import { defineMiddleware } from 'nitro'
import { getRequestURL } from 'nitro/h3'
import { useRuntimeConfig } from 'nitro/runtime-config'
import type { H3Event } from 'nitro/h3'
import { getUserTenantDomain } from '../../../utils/internal/tenant'

interface OpenAPIServer {
  url: string
  description?: string
}

interface OpenAPIDocument {
  openapi: string
  servers?: OpenAPIServer[]
  paths?: Record<string, unknown>
  [key: string]: unknown
}

function isOpenAPIDocument(value: unknown): value is OpenAPIDocument {
  return Boolean(value) && typeof value === 'object' && 'openapi' in (value as object)
}

function joinURLSegments(origin: string, ...segments: (string | undefined)[]): string {
  const path = segments
    .map((segment) => segment?.replace(/^\/+|\/+$/g, '') ?? '')
    .filter((segment) => segment.length > 0)
    .join('/')

  return path ? `${origin}/${path}` : origin
}

async function resolveServer(event: H3Event): Promise<OpenAPIServer> {
  const baseURL = (useRuntimeConfig().app as { baseURL?: string } | undefined)?.baseURL
  const contextPath = c8yManifest.contextPath ?? c8yManifest.name

  // When deployed, the service is reached through the platform proxy under the
  // tenant's public domain at /service/<contextPath> (the proxy strips that
  // prefix, so the service itself only sees internal cluster URLs). Resolve the
  // public domain through the requesting user's tenant.
  if (!import.meta.dev) {
    try {
      const domain = await getUserTenantDomain(event)
      if (domain) {
        return {
          url: joinURLSegments(`https://${domain}`, 'service', contextPath, baseURL),
          description: 'Cumulocity microservice endpoint',
        }
      }
    } catch {
      // Unauthenticated request or domain lookup failure: fall back to
      // request-based resolution below rather than failing the document.
    }
  }

  const requestUrl = getRequestURL(event, { xForwardedHost: true, xForwardedProto: true })

  // Fallback for proxied requests that carry forwarding headers.
  if (event.req.headers.has('x-forwarded-host')) {
    return {
      url: joinURLSegments(requestUrl.origin, 'service', contextPath, baseURL),
      description: 'Cumulocity microservice endpoint',
    }
  }

  return {
    url: joinURLSegments(requestUrl.origin, baseURL),
    description: 'Direct server endpoint',
  }
}

/**
 * Transforms the OpenAPI document generated by Nitro for Cumulocity microservices:
 * strips internal routes (probes, `/_c8y_nitro/**`, the spec/UI routes themselves)
 * and rewrites the advertised server URL to the public tenant endpoint instead of
 * the internal (e.g. cluster-local) host the service listens on.
 */
export default defineMiddleware(async (event, next) => {
  const runtimeConfig = useRuntimeConfig()

  // Registered globally (nitro can't route-scope middleware yet), so bail out
  // for everything that isn't the OpenAPI document route.
  const specRoute = (runtimeConfig as { nitro?: { openAPI?: { route?: string } } }).nitro?.openAPI?.route || '/_openapi.json'
  const baseURL = ((runtimeConfig.app as { baseURL?: string } | undefined)?.baseURL ?? '/').replace(/\/+$/, '')
  if (event.url.pathname !== `${baseURL}${specRoute}`) {
    return next()
  }

  const body = await next()

  if (!isOpenAPIDocument(body)) {
    return body
  }

  const excludedPrefixes = (runtimeConfig.c8yOpenApiExcludeRoutes ?? []) as string[]
  if (body.paths && excludedPrefixes.length > 0) {
    body.paths = Object.fromEntries(
      Object.entries(body.paths).filter(([path]) => !excludedPrefixes.some((prefix) => path.startsWith(prefix))),
    )
  }

  body.servers = [await resolveServer(event)]

  return body
})
