/**
 * Generated by tsnapi — public API snapshot of `c8y-nitro`
 */
// #region Functions
export declare function c8y(): NitroModule;
// #endregion

// #region Default Export
declare function _default(): NitroModule;
export default _default
// #endregion