/**
 * Generated by tsnapi — public API snapshot of `c8y-nitro` */
// Functions
export declare function c8y(): NitroModule;

// Default Export
declare function _default(): NitroModule;
export default _default