/**
 * Generated by tsnapi — public API snapshot of `c8y-nitro/types` */
// Interfaces
export interface C8YAPIClientOptions {
  dir: string;
  contextPath?: string;
}
export interface C8yCacheOptions {
  credentialsTTL?: number;
  defaultTenantOptionsTTL?: number;
  tenantOptions?: C8YTenantOptionKeysCacheConfig;
}
export interface C8yDevOptions {
  injectUser?: boolean;
}
export interface C8YManifest {
  apiVersion: string;
  key: string;
  type: 'MICROSERVICE';
  name: string;
  version: string;
  contextPath?: string;
  provider: Provider;
  billingMode?: 'RESOURCES' | 'SUBSCRIPTION';
  isolation?: 'MULTI_TENANT' | 'PER_TENANT';
  scale?: 'AUTO' | 'NONE';
  replicas?: number;
  resources?: Resources;
  requestedResources?: RequestedResources;
  settings?: Option[];
  settingsCategory?: string;
  requiredRoles?: string[];
  roles?: string[];
  livenessProbe?: Probe;
  readinessProbe?: Probe;
  extensions?: Extension[];
}
export interface C8yNitroModuleOptions {
  dev?: C8yDevOptions;
  scheduler?: C8ySchedulerOptions;
  manifest?: C8YManifestOptions;
  apiClient?: C8YAPIClientOptions;
  zip?: C8YZipOptions;
  cache?: C8yCacheOptions;
  enableTenantOptionsInvalidationRoute?: boolean;
  skipBootstrap?: boolean;
}
export interface C8YRoles {}
export interface C8ySchedulerOptions {
  persistence?: 'memory' | 'inventory';
}
export interface C8YZipOptions {
  name?: string | ((packageName: string, version: string) => string);
  outputDir?: string;
  manifest?: C8YManifestOptions;
}

// Types
export type C8YManifestOptions = Omit<C8YManifest, 'name' | 'version' | 'apiVersion' | 'key' | 'type' | 'provider'>;
export type C8YTenantOptionKey = string;
export type C8YTenantOptionKeysCacheConfig = Partial<Record<C8YTenantOptionKey$1, number>>;