/**
 * Generated by tsnapi — public API snapshot of `c8y-nitro/utils`
 */
// #region Interfaces
export interface ForeignTenantOptionCategory<K extends string = string> {
  option: <Key extends K>(_: ForeignTenantOptionKeyInput<Key>) => TenantOption;
  list: () => Promise<Record<string, string>>;
  setAll: (_: Record<string, string>) => Promise<void>;
  invalidateAll: () => Promise<void>;
  refreshAll: () => Promise<Record<string, string | undefined>>;
}
export interface ScheduledTaskInfo {
  id: string;
  task: string;
  runAt: string;
}
export interface ScheduleTaskOptions {
  payload?: ScheduledTaskPayload;
  context?: ScheduledTaskContext;
  schedule: ScheduledTaskInput;
}
export interface SetEditableOptions {
  targetTenant: string;
}
export interface TenantOption {
  read: () => Promise<string | undefined>;
  set: (_: string) => Promise<void>;
  getOrInsert: (_: string) => Promise<string>;
  delete: () => Promise<void>;
  setEditable: (_: boolean, _: SetEditableOptions) => Promise<void>;
  refresh: () => Promise<string | undefined>;
  invalidate: () => Promise<void>;
}
export interface TenantOptionCategory {
  option: (_: TenantOptionKeyInput) => TenantOption;
  list: () => Promise<Record<string, string>>;
  setAll: (_: Record<string, string>) => Promise<void>;
  invalidateAll: () => Promise<void>;
  refreshAll: () => Promise<Record<string, string | undefined>>;
}
// #endregion

// #region Types
export type ForeignTenantOptionKeyInput<K extends string> = K & (K extends `credentials.${string}` ? never : unknown);
export type ScheduledTaskContext = TaskContext;
export type ScheduledTaskInput = Date | number | string;
export type ScheduledTaskPayload = TaskPayload;
export type TenantOptionKeyInput = C8YTenantOptionKey | (string & {});
// #endregion

// #region Functions
export declare function cancelScheduledTask(_: string): Promise<boolean>;
export declare function hasUserRequiredRole(_: UserRole): EventHandler;
export declare function hasUserRequiredRole(_: UserRole[]): EventHandler;
export declare function isUserFromAllowedTenant(_: string): EventHandler;
export declare function isUserFromAllowedTenant(_: string[]): EventHandler;
export declare function isUserFromDeployedTenant(): EventHandler;
export declare function listScheduledTasks(): Promise<Record<string, ScheduledTaskInfo>>;
export declare function scheduleTask(_: string, _: ScheduleTaskOptions): Promise<ScheduledTaskInfo>;
export declare function useDeployedTenantClient(): Promise<Client>;
export declare function useSubscribedTenantClients(): Promise<Record<string, Client>>;
export declare function useTenantOption(_: Client, _: TenantOptionKeyInput): TenantOption;
export declare function useUser(_: ServerRequest | H3Event): Promise<ICurrentUser>;
export declare function useUserClient(_: ServerRequest | H3Event): Client;
export declare function useUserRoles(_: ServerRequest | H3Event): Promise<string[]>;
export declare function useUserTenantClient(_: ServerRequest | H3Event): Promise<Client>;
export declare function useUserTenantCredentials(_: ServerRequest | H3Event): Promise<ICredentials>;
// #endregion

// #region Variables
export declare const useDeployedTenantCredentials: (() => Promise<ICredentials>) & {
  invalidate: () => Promise<void>;
  refresh: () => Promise<ICredentials>;
};
export declare const useSubscribedTenantCredentials: (() => Promise<TenantCredentials>) & {
  invalidate: () => Promise<void>;
  refresh: () => Promise<TenantCredentials>;
};
export declare const useTenantOptions: UseTenantOptions;
// #endregion

// #region Other
export { createError }
export { createLogger }
export { useLogger }
// #endregion