/**
 * Generated by tsnapi — public API snapshot of `c8y-nitro/utils`
 */
// #region Interfaces
export interface BaseJobInfo {
  name: string;
  task: string;
  concurrency: JobConcurrency;
  nextRun: string | null;
  running: boolean;
}
export interface ForeignTenantOptionCategory<K extends string = string> {
  option: <Key extends K>(_: ForeignTenantOptionKeyInput<Key>) => TenantOption;
  list: () => Promise<Record<string, string>>;
  setAll: (_: Record<string, string>) => Promise<void>;
  invalidateAll: () => Promise<void>;
  refreshAll: () => Promise<Record<string, string | undefined>>;
}
export interface OnceJobInfo extends BaseJobInfo {
  kind: 'once';
  cron: null;
}
export interface RecurringJobInfo extends BaseJobInfo {
  kind: 'recurring';
  cron: string;
  timezone: string;
  nextRuns: string[];
}
export interface ScheduleJobOptions<TTask extends string = string, TPayload = TaskRegistryPayload, TSchedule extends JobSchedule = JobSchedule> {
  name: string;
  task: TTask;
  schedule: TSchedule;
  payload?: TPayload;
  context?: TaskRegistryContext;
  concurrency?: JobConcurrency;
  timezone?: string;
  immediate?: boolean;
  maxRuns?: number;
  replace?: boolean;
}
export interface SetEditableOptions {
  targetTenant: string;
}
export interface TaskEvent<TPayload = TaskRegistryPayload> {
  task: string;
  job?: string;
  payload: TPayload;
  context: TaskRegistryContext;
}
export interface TaskRegistry<TTasks extends TaskMap = {}> {
  createTask: <TName extends string, TPayload extends TaskRegistryPayload = TaskRegistryPayload, TResult = unknown>(_: TName extends keyof TTasks ? never : TName, _: TaskHandler<TPayload, TResult>) => TaskRegistry<TTasks & Record<TName, TaskShape<TPayload, TResult>>>;
  run: <TName extends keyof TTasks & string>(_: TName, _?: {
    payload?: TTasks[TName]['payload'];
    context?: TaskRegistryContext;
  }) => Promise<TTasks[TName]['result']>;
  scheduleJob: <TName extends keyof TTasks & string, TSchedule extends JobSchedule>(_: ScheduleJobOptions<TName, TTasks[TName]['payload'], TSchedule>) => JobInfoFor<TSchedule>;
  triggerJob: <TResult = unknown>(_: string, _?: {
    payload?: TaskRegistryPayload;
    context?: TaskRegistryContext;
  }) => Promise<TResult>;
  cancelJob: (_: string) => boolean;
  listJobs: () => JobInfo[];
  getJob: (_: string) => JobInfo | undefined;
  hasTask: (_: string) => boolean;
}
export interface TaskShape<TPayload = TaskRegistryPayload, TResult = unknown> {
  payload: TPayload;
  result: TResult;
}
export interface TenantOption {
  read: () => Promise<string | undefined>;
  set: (_: string) => Promise<void>;
  getOrInsert: (_: string) => Promise<string>;
  delete: () => Promise<void>;
  setEditable: (_: boolean, _: SetEditableOptions) => Promise<void>;
  refresh: () => Promise<string | undefined>;
  invalidate: () => Promise<void>;
}
export interface TenantOptionCategory {
  option: (_: TenantOptionKeyInput) => TenantOption;
  list: () => Promise<Record<string, string>>;
  setAll: (_: Record<string, string>) => Promise<void>;
  invalidateAll: () => Promise<void>;
  refreshAll: () => Promise<Record<string, string | undefined>>;
}
// #endregion

// #region Types
export type ForeignTenantOptionKeyInput<K extends string> = K & (K extends `credentials.${string}` ? never : unknown);
export type JobConcurrency = 'single' | 'parallel';
export type JobInfo = OnceJobInfo | RecurringJobInfo;
export type JobInfoFor<TSchedule extends JobSchedule> = TSchedule extends {
  cron: string;
} ? RecurringJobInfo : OnceJobInfo;
export type JobSchedule = {
  cron: string;
} | {
  in: number;
} | {
  at: Date | string;
};
export type TaskHandler<TPayload = TaskRegistryPayload, TResult = unknown> = (_: TaskEvent<TPayload>) => TResult | Promise<TResult>;
export type TaskMap = Record<string, TaskShape>;
export type TaskRegistryContext = TaskContext;
export type TaskRegistryPayload = TaskPayload;
export type TenantOptionKeyInput = C8YTenantOptionKey | (string & {});
// #endregion

// #region Functions
export declare function c8yTasks(): TaskRegistry;
export declare function hasUserRequiredRole(_: UserRole): EventHandler;
export declare function hasUserRequiredRole(_: UserRole[]): EventHandler;
export declare function isUserFromAllowedTenant(_: string): EventHandler;
export declare function isUserFromAllowedTenant(_: string[]): EventHandler;
export declare function isUserFromDeployedTenant(): EventHandler;
export declare function useDeployedTenantClient(): Promise<Client>;
export declare function useLogger<T extends object = Record<string, unknown>>(_: HTTPEvent | ServerRequest, _?: string): import("evlog").AuditableLogger<T>;
export declare function useSubscribedTenantClients(): Promise<Record<string, Client>>;
export declare function useTenantOption(_: Client, _: TenantOptionKeyInput): TenantOption;
export declare function useUser(_: ServerRequest | H3Event): Promise<ICurrentUser>;
export declare function useUserClient(_: ServerRequest | H3Event): Client;
export declare function useUserRoles(_: ServerRequest | H3Event): Promise<string[]>;
export declare function useUserTenantClient(_: ServerRequest | H3Event): Promise<Client>;
export declare function useUserTenantCredentials(_: ServerRequest | H3Event): Promise<ICredentials>;
// #endregion

// #region Variables
export declare const createError: typeof createError$1;
export declare const useDeployedTenantCredentials: (() => Promise<ICredentials>) & {
  invalidate: () => Promise<void>;
  refresh: () => Promise<ICredentials>;
};
export declare const useSubscribedTenantCredentials: (() => Promise<TenantCredentials>) & {
  invalidate: () => Promise<void>;
  refresh: () => Promise<TenantCredentials>;
};
export declare const useTenantOptions: UseTenantOptions;
// #endregion

// #region Other
export { createLogger }
// #endregion