/**
 * Generated by tsnapi — public API snapshot of `c8y-nitro/utils`
 */
// #region Interfaces
export interface ScheduledTaskInfo {
  id: string;
  task: string;
  runAt: string;
}
export interface ScheduleTaskOptions {
  payload?: ScheduledTaskPayload;
  context?: ScheduledTaskContext;
  schedule: ScheduledTaskInput;
}
// #endregion

// #region Types
export type ScheduledTaskContext = TaskContext;
export type ScheduledTaskInput = Date | number | string;
export type ScheduledTaskPayload = TaskPayload;
// #endregion

// #region Functions
export declare function cancelScheduledTask(_: string): Promise<boolean>;
export declare function hasUserRequiredRole(_: UserRole): EventHandler;
export declare function hasUserRequiredRole(_: UserRole[]): EventHandler;
export declare function isUserFromAllowedTenant(_: string): EventHandler;
export declare function isUserFromAllowedTenant(_: string[]): EventHandler;
export declare function isUserFromDeployedTenant(): EventHandler;
export declare function listScheduledTasks(): Promise<Record<string, ScheduledTaskInfo>>;
export declare function scheduleTask(_: string, _: ScheduleTaskOptions): Promise<ScheduledTaskInfo>;
export declare function useDeployedTenantClient(): Promise<Client>;
export declare function useSubscribedTenantClients(): Promise<Record<string, Client>>;
export declare function useUser(_: ServerRequest | H3Event): Promise<ICurrentUser>;
export declare function useUserClient(_: ServerRequest | H3Event): Client;
export declare function useUserRoles(_: ServerRequest | H3Event): Promise<string[]>;
export declare function useUserTenantClient(_: ServerRequest | H3Event): Promise<Client>;
export declare function useUserTenantCredentials(_: ServerRequest | H3Event): Promise<ICredentials>;
// #endregion

// #region Variables
export declare const useDeployedTenantCredentials: (() => Promise<ICredentials>) & {
  invalidate: () => Promise<void>;
  refresh: () => Promise<ICredentials>;
};
export declare const useSubscribedTenantCredentials: (() => Promise<Record<string, ICredentials>>) & {
  invalidate: () => Promise<void>;
  refresh: () => Promise<Record<string, ICredentials>>;
};
export declare const useTenantOption: ((key: C8YTenantOptionKey) => Promise<string | undefined>) & {
  invalidate: (key: C8YTenantOptionKey) => Promise<void>;
  refresh: (key: C8YTenantOptionKey) => Promise<string | undefined>;
  invalidateAll: () => Promise<void>;
  refreshAll: () => Promise<Record<string, string | undefined>>;
};
// #endregion

// #region Other
export { createError }
export { createLogger }
export { useLogger }
// #endregion