/**
 * Generates `src/types/roles.generated.ts` — a union of the Cumulocity platform
 * roles ("required roles") discovered in the public core OpenAPI specification.
 *
 * These are the `ROLE_*` strings you have to look up in the c8y docs whenever a
 * route says e.g. "Required roles: ROLE_ALARM_ADMIN". Generating them gives
 * autocomplete for `requiredRoles` in the manifest while still allowing any
 * unknown string as a fallback (see `C8YRole` in `src/types/roles.ts`).
 *
 * Usage:
 *   node scripts/generate-roles.ts            # fetch the live spec
 *   node scripts/generate-roles.ts --file x   # parse a local spec (offline)
 *
 * Node >= 26 runs this TypeScript file directly, no build step needed.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import process from 'node:process'
import { consola } from 'consola'

const SPEC_URL = 'https://cumulocity.com/api/core/dist/c8y-oas.json'
const ROLE_PATTERN = /ROLE_[A-Z0-9_]+/g

const scriptDir = dirname(fileURLToPath(import.meta.url))
const outputPath = join(scriptDir, '..', 'src', 'types', 'roles.generated.ts')

function parseArgs(argv: string[]): { file?: string } {
  const fileFlag = argv.indexOf('--file')
  if (fileFlag !== -1) {
    const value = argv[fileFlag + 1]
    if (!value) {
      throw new Error('--file requires a path argument')
    }
    return { file: value }
  }
  return {}
}

async function loadSpec(file?: string): Promise<{ raw: string, version: string, source: string }> {
  if (file) {
    const raw = await readFile(file, 'utf8')
    return { raw, version: readVersion(raw), source: file }
  }

  const response = await fetch(SPEC_URL)
  if (!response.ok) {
    throw new Error(`Failed to download spec: ${response.status} ${response.statusText}`)
  }
  const raw = await response.text()
  return { raw, version: readVersion(raw), source: SPEC_URL }
}

function readVersion(raw: string): string {
  try {
    return (JSON.parse(raw) as { info?: { version?: string } }).info?.version ?? 'unknown'
  } catch {
    return 'unknown'
  }
}

function extractRoles(raw: string): string[] {
  const roles = new Set(raw.match(ROLE_PATTERN) ?? [])
  return [...roles].sort((a, b) => a.localeCompare(b))
}

function renderFile(roles: string[], source: string, version: string): string {
  const union = roles.length > 0
    ? roles.map((role) => `  | '${role}'`).join('\n')
    : '  never'

  return `/**
 * AUTO-GENERATED by scripts/generate-roles.ts — do not edit by hand.
 *
 * Source: ${source}
 * Spec version: ${version}
 * Known roles: ${roles.length}
 *
 * Run \`pnpm gen:roles\` to regenerate.
 */

/**
 * Cumulocity platform roles ("required roles") known from the core OpenAPI spec.
 */
export type C8YKnownRole =
${union}
`
}

async function main(): Promise<void> {
  const { file } = parseArgs(process.argv.slice(2))

  consola.info(`Loading OpenAPI spec from ${file ?? SPEC_URL} ...`)
  const { raw, version, source } = await loadSpec(file)

  const roles = extractRoles(raw)
  if (roles.length === 0) {
    throw new Error('No ROLE_* tokens found in the spec — refusing to overwrite with an empty union.')
  }

  const previous = await readFile(outputPath, 'utf8').catch(() => '')
  const previousRoles = new Set(previous.match(/ROLE_[A-Z0-9_]+/g) ?? [])
  const added = roles.filter((role) => !previousRoles.has(role))
  const removed = [...previousRoles].filter((role) => !roles.includes(role))

  await writeFile(outputPath, renderFile(roles, source, version), 'utf8')

  consola.success(`Wrote ${roles.length} roles to ${outputPath} (spec version: ${version})`)
  if (added.length > 0) {
    consola.log(`  + added:   ${added.join(', ')}`)
  }
  if (removed.length > 0) {
    consola.log(`  - removed: ${removed.join(', ')}`)
  }
  if (added.length === 0 && removed.length === 0) {
    consola.log('  no changes')
  }
}

main().catch((error: unknown) => {
  consola.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
