import { vol, fs as memFs } from 'memfs'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { setupRuntime } from '../../src/module/runtime'

// Mock fs modules with memfs
vi.mock('fs', () => ({ ...memFs, default: memFs }))
vi.mock('fs/promises', () => memFs.promises)

// Create a minimal mock Nitro instance
function createMockNitro(
  rootDir = '/project',
  generatedTypesDir = 'node_modules/.nitro/types',
) {
  return {
    options: {
      rootDir,
      typescript: {
        generatedTypesDir,
      },
      virtual: {},
    },
    logger: {
      debug: vi.fn(),
    },
  } as unknown as Parameters<typeof setupRuntime>[0]
}

describe('setupRuntime', () => {
  beforeEach(() => {
    vol.reset()
  })

  describe('type generation', () => {
    it('should generate types file with no roles or settings', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {})

      const generatedFiles = vol.toJSON()
      const typesPath = '/project/node_modules/.nitro/types/c8y-nitro.d.ts'

      expect(generatedFiles).toHaveProperty(typesPath)

      const content = generatedFiles[typesPath] as string
      expect(content).toContain('// generated by c8y-nitro')
      expect(content).toContain('declare module \'c8y-nitro/types\'')
      expect(content).toContain('interface C8YRoles {')
      expect(content).toContain('type C8YTenantOptionKey = never')
      expect(content).toContain('type C8YTenantOptionKeysCacheConfig = Partial<Record<C8YTenantOptionKey, number>>')
      expect(content).toContain('declare module \'c8y-nitro/runtime\'')
      expect(content).toContain('export const c8yRoles: C8YRoles')
      expect(content).toContain('export const c8yTenantOptionKeys: readonly []')
    })

    it('should generate types file with roles', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {
        roles: ['ROLE_APPLICATION_ADMIN', 'ROLE_MEASUREMENT_READ'],
      })

      const generatedFiles = vol.toJSON()
      const typesPath = '/project/node_modules/.nitro/types/c8y-nitro.d.ts'
      const content = generatedFiles[typesPath] as string

      // Check that roles are properly typed
      expect(content).toContain('\'ROLE_APPLICATION_ADMIN\': \'ROLE_APPLICATION_ADMIN\'')
      expect(content).toContain('\'ROLE_MEASUREMENT_READ\': \'ROLE_MEASUREMENT_READ\'')
      expect(content).toContain('export const c8yTenantOptionKeys: readonly []')
    })

    it('should generate types file with tenant option keys', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {
        settings: [
          { key: 'feature.enabled', defaultValue: 'true' },
          { key: 'max.connections', defaultValue: '10' },
        ],
      })

      const generatedFiles = vol.toJSON()
      const typesPath = '/project/node_modules/.nitro/types/c8y-nitro.d.ts'
      const content = generatedFiles[typesPath] as string

      // Check that tenant option keys are properly typed
      expect(content).toContain('type C8YTenantOptionKey = \'feature.enabled\' | \'max.connections\'')
      expect(content).toContain('export const c8yTenantOptionKeys: readonly [\'feature.enabled\', \'max.connections\']')
    })

    it('should generate types file with both roles and settings', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {
        roles: ['ROLE_ADMIN', 'ROLE_USER'],
        settings: [
          { key: 'api.timeout', defaultValue: '30' },
          { key: 'cache.ttl', defaultValue: '60' },
        ],
      })

      const generatedFiles = vol.toJSON()
      const typesPath = '/project/node_modules/.nitro/types/c8y-nitro.d.ts'
      const content = generatedFiles[typesPath] as string

      // Check roles
      expect(content).toContain('\'ROLE_ADMIN\': \'ROLE_ADMIN\'')
      expect(content).toContain('\'ROLE_USER\': \'ROLE_USER\'')

      // Check tenant option keys
      expect(content).toContain('type C8YTenantOptionKey = \'api.timeout\' | \'cache.ttl\'')
      expect(content).toContain('export const c8yTenantOptionKeys: readonly [\'api.timeout\', \'cache.ttl\']')
    })

    it('should respect custom generatedTypesDir', () => {
      const nitro = createMockNitro('/project', 'custom-types')

      setupRuntime(nitro, {})

      const generatedFiles = vol.toJSON()
      const typesPath = '/project/custom-types/c8y-nitro.d.ts'

      expect(generatedFiles).toHaveProperty(typesPath)
    })

    it('should create directory recursively', () => {
      const nitro = createMockNitro('/project', 'nested/deep/types')

      setupRuntime(nitro, {})

      const generatedFiles = vol.toJSON()
      const typesPath = '/project/nested/deep/types/c8y-nitro.d.ts'

      expect(generatedFiles).toHaveProperty(typesPath)
    })

    it('should not include legacy separate type files', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {
        roles: ['ROLE_ADMIN'],
        settings: [{ key: 'test.key', defaultValue: 'value' }],
      })

      const generatedFiles = vol.toJSON()

      // Should only have one consolidated file
      expect(Object.keys(generatedFiles)).toHaveLength(1)
      expect(generatedFiles).toHaveProperty('/project/node_modules/.nitro/types/c8y-nitro.d.ts')

      // Should NOT have legacy files
      expect(generatedFiles).not.toHaveProperty('/project/node_modules/.nitro/types/c8y-roles.d.ts')
      expect(generatedFiles).not.toHaveProperty('/project/node_modules/.nitro/types/c8y-tenant-options.d.ts')
    })
  })

  describe('virtual module generation', () => {
    it('should generate virtual module with empty roles and keys', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {})

      const virtualModule = nitro.options.virtual['c8y-nitro/runtime']

      expect(virtualModule).toBeDefined()
      expect(virtualModule).toContain('export const c8yRoles = {')
      expect(virtualModule).toContain('export const c8yTenantOptionKeys = []')
    })

    it('should generate virtual module with roles', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {
        roles: ['ROLE_ADMIN', 'ROLE_USER'],
      })

      const virtualModule = nitro.options.virtual['c8y-nitro/runtime']

      expect(virtualModule).toContain('\'ROLE_ADMIN\': \'ROLE_ADMIN\',')
      expect(virtualModule).toContain('\'ROLE_USER\': \'ROLE_USER\',')
      expect(virtualModule).toContain('export const c8yTenantOptionKeys = []')
    })

    it('should generate virtual module with tenant option keys', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {
        settings: [
          { key: 'key1', defaultValue: 'value1' },
          { key: 'key2', defaultValue: 'value2' },
        ],
      })

      const virtualModule = nitro.options.virtual['c8y-nitro/runtime']

      expect(virtualModule).toContain('export const c8yTenantOptionKeys = [\'key1\', \'key2\']')
    })

    it('should generate virtual module with both roles and keys', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {
        roles: ['ROLE_TEST'],
        settings: [{ key: 'test.key', defaultValue: 'value' }],
      })

      const virtualModule = nitro.options.virtual['c8y-nitro/runtime']

      expect(virtualModule).toContain('\'ROLE_TEST\': \'ROLE_TEST\',')
      expect(virtualModule).toContain('export const c8yTenantOptionKeys = [\'test.key\']')
    })
  })

  describe('logger integration', () => {
    it('should log debug messages', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {})

      expect(nitro.logger.debug).toHaveBeenCalledWith('Setting up C8Y nitro runtime')
      expect(nitro.logger.debug).toHaveBeenCalledWith(
        expect.stringContaining('Written C8Y types to'),
      )
    })
  })

  describe('edge cases', () => {
    it('should handle special characters in role names', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {
        roles: ['ROLE_WITH-DASH', 'ROLE_WITH_UNDERSCORE'],
      })

      const generatedFiles = vol.toJSON()
      const content = generatedFiles['/project/node_modules/.nitro/types/c8y-nitro.d.ts'] as string

      expect(content).toContain('\'ROLE_WITH-DASH\': \'ROLE_WITH-DASH\'')
      expect(content).toContain('\'ROLE_WITH_UNDERSCORE\': \'ROLE_WITH_UNDERSCORE\'')
    })

    it('should handle special characters in tenant option keys', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {
        settings: [
          { key: 'key.with.dots', defaultValue: 'value' },
          { key: 'key-with-dashes', defaultValue: 'value' },
          { key: 'key_with_underscores', defaultValue: 'value' },
        ],
      })

      const generatedFiles = vol.toJSON()
      const content = generatedFiles['/project/node_modules/.nitro/types/c8y-nitro.d.ts'] as string

      expect(content).toContain('\'key.with.dots\'')
      expect(content).toContain('\'key-with-dashes\'')
      expect(content).toContain('\'key_with_underscores\'')
    })

    it('should handle single role', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {
        roles: ['ROLE_SINGLE'],
      })

      const generatedFiles = vol.toJSON()
      const content = generatedFiles['/project/node_modules/.nitro/types/c8y-nitro.d.ts'] as string

      expect(content).toContain('\'ROLE_SINGLE\': \'ROLE_SINGLE\'')
    })

    it('should handle single tenant option key', () => {
      const nitro = createMockNitro()

      setupRuntime(nitro, {
        settings: [{ key: 'single.key', defaultValue: 'value' }],
      })

      const generatedFiles = vol.toJSON()
      const content = generatedFiles['/project/node_modules/.nitro/types/c8y-nitro.d.ts'] as string

      expect(content).toContain('type C8YTenantOptionKey = \'single.key\'')
      expect(content).toContain('export const c8yTenantOptionKeys: readonly [\'single.key\']')
    })

    it('should overwrite existing types file', () => {
      const nitro = createMockNitro()

      // Create existing file
      vol.fromJSON({
        '/project/node_modules/.nitro/types/c8y-nitro.d.ts': 'old content',
      })

      setupRuntime(nitro, {
        roles: ['ROLE_NEW'],
      })

      const generatedFiles = vol.toJSON()
      const content = generatedFiles['/project/node_modules/.nitro/types/c8y-nitro.d.ts'] as string

      expect(content).not.toContain('old content')
      expect(content).toContain('\'ROLE_NEW\': \'ROLE_NEW\'')
    })
  })
})
