import type { Nitro } from 'nitro/types'
import type { C8YManifestOptions } from '../types'
import { join } from 'pathe'
import { writeFileSync, mkdirSync } from 'fs'

export function setupRuntime(nitro: Nitro, manifestOptions: C8YManifestOptions = {}): void {
  nitro.logger.debug('Setting up C8Y nitro runtime')
  const roles = manifestOptions.roles ?? []

  // write roles types into
  const completeTypesDir = join(nitro.options.rootDir, nitro.options.typescript.generatedTypesDir ?? 'node_modules/.nitro/types')

  // in the future we have to augment the types with the virtual imports to support all runtime logic

  // create contents for file called c8y-roles.d.ts
  const rolesTypeFile = join(completeTypesDir, 'c8y-nitro-roles.d.ts')
  const rolesTypeContent
    = `// generated by c8y-nitro
declare module 'c8y-nitro/types' {
  interface C8YRoles {
${roles.map((role) => `    '${role}': '${role}';`).join('\n')}
  }
}
declare module 'c8y-nitro/runtime' {
  import type { C8YRoles } from 'c8y-nitro/types';
  
  export interface C8yRuntimeConfig {
    cache: {
      credentialsTTL: number;
    };
  }
  
  export const c8yRoles: C8YRoles;
  export const c8yConfig: C8yRuntimeConfig;
}`

  // augment the virtual module "c8y-nitro/runtime" to export the roles
  nitro.options.virtual['c8y-nitro/runtime']
    = `
export const c8yRoles = {
${roles.map((role) => `  '${role}': '${role}',`).join('\n')}
}
`

  // write file
  mkdirSync(completeTypesDir, { recursive: true })
  writeFileSync(rolesTypeFile, rolesTypeContent, { encoding: 'utf-8' })
  nitro.logger.debug(`Written C8Y roles types to ${rolesTypeFile}`)
}
