import type { Nitro } from 'nitro/types'
import type { C8YManifest } from '../types'
import { join } from 'pathe'
import { writeFileSync, mkdirSync } from 'fs'

export function setupRuntime(nitro: Nitro, manifest: C8YManifest): void {
  nitro.logger.debug('Setting up C8Y nitro runtime')
  const roles = manifest.roles ?? []
  const settings = manifest.settings ?? []
  const settingKeys = settings.map((s) => s.key)
  // Mirror the runtime category resolution (see setupRuntimeConfig) so the
  // generated literal matches what `useTenantOption*` uses at runtime.
  const settingsCategory = manifest.settingsCategory ?? manifest.contextPath ?? manifest.name

  const completeTypesDir = join(nitro.options.rootDir, nitro.options.typescript.generatedTypesDir ?? 'node_modules/.nitro/types')

  // Generate all types in a single file
  const typesFile = join(completeTypesDir, 'c8y-nitro.d.ts')
  const typesContent = `// generated by c8y-nitro
declare module 'c8y-nitro/types' {
  interface C8YRoles {
${roles.map((role) => `    '${role}': '${role}';`).join('\n')}
  }
  type C8YTenantOptionKey = ${settingKeys.length > 0 ? `${settingKeys.map((k) => `'${k}'`).join(' | ')}` : 'never'}
  type C8YTenantOptionKeysCacheConfig = Partial<Record<C8YTenantOptionKey, number>>;
  type C8YSettingsCategory = ${settingsCategory ? `'${settingsCategory}'` : 'string'};
}

declare module 'c8y-nitro/runtime' {
  import type { C8YRoles, C8yManifest } from 'c8y-nitro/types';
  export const c8yRoles: C8YRoles;
  export const c8yTenantOptionKeys: readonly [${settingKeys.map((key) => `'${key}'`).join(', ')}];
  export const c8yManifest: C8yManifest;
}`

  // Generate virtual module with runtime exports
  nitro.options.virtual['c8y-nitro/runtime'] = `
export const c8yRoles = {
${roles.map((role) => `  '${role}': '${role}',`).join('\n')}
}

export const c8yManifest = ${JSON.stringify(manifest, null, 2)}

export const c8yTenantOptionKeys = [${settingKeys.map((key) => `'${key}'`).join(', ')}]
`

  // Write single type file
  mkdirSync(completeTypesDir, { recursive: true })
  writeFileSync(typesFile, typesContent, { encoding: 'utf-8' })

  nitro.logger.debug(`Written C8Y types to ${typesFile}`)
}
